### PR TITLE
Add migration from glide

### PR DESCRIPTION
**Pull request by grafov**
Migration of glide.lock into vendor.json.

### CODE REVIEW

**Comment by kardianos** [comment]
Please vendor the yaml package.

**Comment by grafov** [comment]
Firstly I had used glide.yaml for migration of my project but found it has missed many subdependencies. Glide can recursively find dependency packages so usually glide.yaml consists only from top level dependencies. Secondly I have used glide.lock and was satisfied with result. Sure if you want to convert repository without glide.lock you will be need to run glide and generate a new glide.lock first. Probably the best way is check both these configs: if glide.lock exists then use it else fallback to glide.yaml. I'll add it to this PR.

**Comment by kardianos** [comment]
Yeah, I'm fine with this PR. Just make sure you run `govendor add +e` to vendor the yaml package you use in it.

**Comment by grafov** [comment]
Ups I understood your first comment in a wrong way :\ I have added the yaml package to this PR.

**Pull request merged**
