### PR TITLE
support negative FileTag

### PR DESCRIPTION
**Pull request by flisky**

### CODE REVIEW

**Comment by flisky** [comment]
Actually, `go1.8` means go1.8 onward, while `!go1.8` means go1.7 and backward.

May I go further to support this? Does this make sense to you, @kardianos?

**Comment by kardianos** [comment]
@flisky I'm sorry I missed this. Do you still want this closed or would you like to re-open this?

**Comment by flisky** [comment]
Re-opened. However, I'm not sure that we should go deeper to enhance this feature.

**Comment by kardianos** [comment]
I think this is good to have. I need to clear my head and look at it more carefully though (Friday afternoon here). Thanks for this :).

**Pull request merged**
