### PR TITLE
add docs for go modules

### PR DESCRIPTION
**Pull request by kaey**
Modules are better than vendoring in every way,
let's help our users learn about SIV earlier.

### CODE REVIEW

**Comment by kaey** [comment]
@kardianos PTAL

**Comment by kardianos** [comment]
Remove ref to vgo, say go modules. Use go command, not vgo. Add in current way to force build to use vendor folder for build.

I fully support modules, I haven't switched my projects because lack of tool support, this is being worked on.  I'd wait until 1.12.

**Comment by kaey** [comment]
>Add in current way to force build to use vendor folder for build.

Do you mean to globally export GOFLAGS="-mod=vendor"? I dislike that because I use modules without vendoring in some projects which I don't develop myself, so I'd need to make an alias to opt-out of vendoring. It's possible. but doesn't make much sense - linters won't work outside of GOPATH anyway and if inside GOPATH - vendor is always used for builds.
This is why I made that vgo alias just to manage deps when working on projects inside GOPATH (and it's not needed when working outside GOPATH, but doesn't break anything)

**Comment by kardianos** [comment]
@kaey I think it is a good idea for people to be aware of modules at this point in time. I think a simple note pointing to some of the resources would be great.

I think your note wording is just a bit too strong at this point. I think I would make the following points:
 * go modules is the future. Look forward to it, start trying it out today in go1.11.
 * go modules will land officially, along with many more supported tools in go1.12.
 * go modules makes GOPATH optional.
 * go modules makes the vendor folder optional, but still allows building from the vendor folder with `-mod=vendor`.

Lastly, if you give an alias, I would call out this is a bash/*nix feature, and developing outside of GOPATH this is on automatically. Though really, I would just omit this part entirely and point users to the go modules reference wiki.

**Comment by kardianos** [comment]
Thanks @kaey . I added a note about Go modules in the readme.

**Pull request closed without merging**
